#!/usr/bin/env bash
# display info

check_subdomain() {
    SUB_DOMAIN=$1
    dig_output=$(dig "$SUB_DOMAIN.$domain" +short)
    RECORD_TYPE=$(dig "$SUB_DOMAIN.$domain" +short | awk 'NR==1{print $4}')

    if [ -z "$dig_output" ]; then
        DESTINATION="N/A"
    else
        DESTINATION="$dig_output"
    fi

    echo "The subdomain $SUB_DOMAIN is a A$RECORD_TYPE record and points to $DESTINATION"
}

# Main script
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    # Display information for default subdomains in the specified order
    check_subdomain "www"
    check_subdomain "lb-01"
    check_subdomain "web-01"
    check_subdomain "web-02"
else
    # Display information for the specified subdomain
    check_subdomain "$subdomain"
fi
