#!/usr/bin/env bash
# configure domain zone and display information about subdomains

print_domain () {
    answ=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $answ" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  print_domain "$1" "www"
  print_domain "$1" "lb-01"
  print_domain "$1" "web-01"
  print_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  print_domain "$1" "$2"
fi
