#!/usr/bin/env bash
# installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
cd /var/www/ || return
sudo chmod 777 html
echo "Hello World!" > html/index.html
sudo chmod 755 html
cd ~ || return
sudo service nginx restart
