#!/usr/bin/env bash
#not_found_page_404
sudo apt-get -y update
sudo apt-get -y install ngnix
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sed -i "46irewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx start
