#!/usr/bin/env bash
# 7 lines or less short and sweet
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
service nginx restart
pgrep nginx > /dev/null && nc -z 0 8080
